### ISSUE TITLE
glob() got an unexpected keyword argument 'root_dir'

### ISSUE THREAD

**Issue by modusCell** [Nuked88/ComfyUI-N-Nodes#25]
Traceback (most recent call last):
  File "/Users/xxxxxxx/stable-diffusion-comfy/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/xxxxxxx/stable-diffusion-comfy/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 18, in <module>
    files = glob.glob("*.py", root_dir=py, recursive=False)
TypeError: glob() got an unexpected keyword argument 'root_dir'

0.0 seconds (IMPORT FAILED): /Users/xxxxxxx/stable-diffusion-comfy/custom_nodes/ComfyUI-N-Nodes

**Comment by Nuked88** [comment]
You are using a python version more older than 3.10, I will try to fix that lone but I'm not sure about the compatibility of the rest of the code.

**Comment by modusCell** [comment]
@Nuked88, I have python 3.10 and 3.11 installed on my mac via Brew (sorry I should have tell you that i am using macOS).

modus@MoMBPM3 stable-diffusion-comfy % python3 --version
Python 3.11.6

**Comment by Nuked88** [comment]
uhm idk... i know that 'root_dir' has been introduced in 3.10 and is still available in 3.11 as you can see [here](https://docs.python.org/3.11/library/glob.html)

If you do ./venv/bin/python --version? is still 3.11.6?
In windows i have the same version and it's working fine

**Comment by modusCell** [comment]
@Nuked88 I do apologise for wasting your time, I should have check that first thing first. updated venv to 3.11 and install 3.11  site packages. all seems in order! 
Appreciated your time

**Comment by Nuked88** [comment]
Don't worry! The important thing is that you've solved the problem!
