### ISSUE TITLE
[BUG] HTTP error 404

### ISSUE THREAD

**Issue by Rorutop** [Nuked88/ComfyUI-N-Nodes#40]
The ComfyUI-N-Nodes was trying to install the packages on startup, but llama-cpp cannot be installed because of this

 ERROR: HTTP error 404 while getting https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl
ERROR: Could not install requirement llama-cpp-python==0.2.20 from https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl for URL https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl
Error while installing LLAMA: Command '['/home/studio-lab-user/.conda/envs/default/bin/python', '-m', 'pip', 'install', 'https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl']' returned non-zero exit status 1.

full logs:
```
** ComfyUI startup time: 2024-02-26 08:48:40.389952
** Platform: Linux
** Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
** Python executable: /home/studio-lab-user/.conda/envs/default/bin/python
** Log path: /home/studio-lab-user/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI-Manager


◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼
[ZROK] environment already enabled.
[ZROK] https://???
◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼◼

Total VRAM 14931 MB, total RAM 15731 MB
xformers version: 0.0.22.post4+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
### Loading: ComfyUI-Manager (V2.8)
### ComfyUI Revision: 2019 [ca7c310a] | Released on '2024-02-25'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Making the "web\extensions\FizzleDorf" folder
Update to javascripts files detected
Copying Folder here to satisfy init, eventually I'll have stuff in here..txt to extensions folder
FizzleDorf Custom Nodes: Loaded
WAS Node Suite: Created default conf file at `/home/studio-lab-user/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json`.
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/home/studio-lab-user/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 212 nodes successfully.

	"Don't wait. The time will never be just right." - Napoleon Hill

[ReActor] - STATUS - Running v0.4.1-b11 in ComfyUI
Torch version: 2.1.0+cu118
Current version of packaging: 23.1
Installing cpuinfo...
Collecting py-cpuinfo
  Downloading py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Installing collected packages: py-cpuinfo
Successfully installed py-cpuinfo-9.0.0
Current version of git: 3.1.42
Installing moviepy...
Collecting moviepy
  Downloading moviepy-1.0.3.tar.gz (388 kB)
     |████████████████████████████████| 388 kB 4.4 MB/s eta 0:00:01
Collecting decorator<5.0,>=4.0.2
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: tqdm<5.0,>=4.11.2 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from moviepy) (4.66.2)
Requirement already satisfied: requests<3.0,>=2.8.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from moviepy) (2.31.0)
Collecting proglog<=1.0.0
  Downloading proglog-0.1.10-py3-none-any.whl (6.1 kB)
Requirement already satisfied: numpy>=1.17.3 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from moviepy) (1.24.4)
Requirement already satisfied: imageio<3.0,>=2.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from moviepy) (2.34.0)
Requirement already satisfied: imageio_ffmpeg>=0.2.0 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from moviepy) (0.4.9)
Requirement already satisfied: pillow>=8.3.2 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from imageio<3.0,>=2.5->moviepy) (9.5.0)
Requirement already satisfied: setuptools in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from imageio_ffmpeg>=0.2.0->moviepy) (68.0.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (1.26.18)
Requirement already satisfied: idna<4,>=2.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (2024.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests<3.0,>=2.8.1->moviepy) (3.2.0)
Building wheels for collected packages: moviepy
  Building wheel for moviepy (setup.py) ... done
  Created wheel for moviepy: filename=moviepy-1.0.3-py3-none-any.whl size=110721 sha256=8131d5569cc70569f066134b4c3520d44134cb1d16af9371ca05728f497ae140
  Stored in directory: /tmp/pip-ephem-wheel-cache-0dlcm9yh/wheels/96/32/2d/e10123bd88fbfc02fed53cc18c80a171d3c87479ed845fa7c1
Successfully built moviepy
Installing collected packages: proglog, decorator, moviepy
  Attempting uninstall: decorator
    Found existing installation: decorator 5.1.1
    Uninstalling decorator-5.1.1:
      Successfully uninstalled decorator-5.1.1
Successfully installed decorator-4.4.2 moviepy-1.0.3 proglog-0.1.10
Current version of cv2: 4.7.0
Installing skbuild...
Collecting scikit-build
  Downloading scikit_build-0.17.6-py3-none-any.whl (84 kB)
     |████████████████████████████████| 84 kB 4.9 MB/s eta 0:00:01
Requirement already satisfied: setuptools>=42.0.0 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from scikit-build) (68.0.0)
Requirement already satisfied: distro in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from scikit-build) (1.9.0)
Requirement already satisfied: wheel>=0.32.0 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from scikit-build) (0.41.1)
Requirement already satisfied: packaging in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from scikit-build) (23.1)
Requirement already satisfied: tomli in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from scikit-build) (2.0.1)
Installing collected packages: scikit-build
Successfully installed scikit-build-0.17.6
Version of typing: Version information not found
Installing diskcache...
Collecting diskcache
  Downloading diskcache-5.6.3-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 3.8 MB/s eta 0:00:011
Installing collected packages: diskcache
Successfully installed diskcache-5.6.3
Installing llama_cpp...
Python version: 310
OS: Linux
OS bit: 64
Platform tag: cp310-cp310-manylinux_2_31_x86_64
Collecting llama-cpp-python==0.2.20
  ERROR: HTTP error 404 while getting https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl
ERROR: Could not install requirement llama-cpp-python==0.2.20 from https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl for URL https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl
Error while installing LLAMA: Command '['/home/studio-lab-user/.conda/envs/default/bin/python', '-m', 'pip', 'install', 'https://github.com/abetlen/llama-cpp-python/releases/download/v0.2.20/llama_cpp_python-0.2.20-cp310-cp310-manylinux_2_31_x86_64.whl']' returned non-zero exit status 1.
Current version of timm: 0.4.12
Updating timm to version 0.9.12...
Collecting timm==0.9.12
  Downloading timm-0.9.12-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 5.0 MB/s eta 0:00:01
Requirement already satisfied: huggingface-hub in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from timm==0.9.12) (0.20.3)
Requirement already satisfied: safetensors in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from timm==0.9.12) (0.4.2)
Requirement already satisfied: pyyaml in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from timm==0.9.12) (6.0.1)
Requirement already satisfied: torchvision in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from timm==0.9.12) (0.16.0+cu118)
Requirement already satisfied: torch>=1.7 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from timm==0.9.12) (2.1.0+cu118)
Requirement already satisfied: filelock in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torch>=1.7->timm==0.9.12) (3.13.1)
Requirement already satisfied: fsspec in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torch>=1.7->timm==0.9.12) (2024.2.0)
Requirement already satisfied: sympy in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torch>=1.7->timm==0.9.12) (1.12)
Requirement already satisfied: typing-extensions in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torch>=1.7->timm==0.9.12) (4.7.1)
Requirement already satisfied: jinja2 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torch>=1.7->timm==0.9.12) (3.1.2)
Requirement already satisfied: networkx in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torch>=1.7->timm==0.9.12) (3.2.1)
Requirement already satisfied: triton==2.1.0 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torch>=1.7->timm==0.9.12) (2.1.0)
Requirement already satisfied: tqdm>=4.42.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from huggingface-hub->timm==0.9.12) (4.66.2)
Requirement already satisfied: packaging>=20.9 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from huggingface-hub->timm==0.9.12) (23.1)
Requirement already satisfied: requests in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from huggingface-hub->timm==0.9.12) (2.31.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from jinja2->torch>=1.7->timm==0.9.12) (2.1.3)
Requirement already satisfied: idna<4,>=2.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests->huggingface-hub->timm==0.9.12) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests->huggingface-hub->timm==0.9.12) (3.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests->huggingface-hub->timm==0.9.12) (2024.2.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from requests->huggingface-hub->timm==0.9.12) (1.26.18)
Requirement already satisfied: mpmath>=0.19 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from sympy->torch>=1.7->timm==0.9.12) (1.3.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torchvision->timm==0.9.12) (9.5.0)
Requirement already satisfied: numpy in /home/studio-lab-user/.conda/envs/default/lib/python3.10/site-packages (from torchvision->timm==0.9.12) (1.24.4)
Installing collected packages: timm
  Attempting uninstall: timm
    Found existing installation: timm 0.4.12
    Uninstalling timm-0.4.12:
      Successfully uninstalled timm-0.4.12
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
clip-interrogator 0.5.5 requires transformers<=4.26.1,>=4.15.0, but you have transformers 4.36.2 which is incompatible.
blip-ci 0.0.5 requires timm==0.4.12, but you have timm 0.9.12 which is incompatible.
Successfully installed timm-0.9.12
timm updated successfully to version 0.9.12
Downloading dependencies...
Traceback (most recent call last):
  File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 69, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI-N-Nodes/py/gptcpp_node.py", line 4, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
```

**Comment by Rorutop** [comment]
Works by installing it manually, but i wish there is no image input for it

**Comment by Nuked88** [comment]
Yes, I was sure something like this would happen sooner or later.
It is because it is detecting that the operating system has the tag "manylinux_2_31_x86_64" but there is no package for llama-cpp-python like that since there is "manylinux_2_17_x86_64". 
I need some time to study an alternative since I don't know how to solve it right away.

**Comment by Nuked88** [comment]
But image IS optional when you are using normal models, is mandatory only with llava and moondream models

**Comment by Rorutop** [comment]
Oh apologies, I forgot what llava does lol
Base models work, noice..
You could close this issue when the HTTP error 404 is fixed.

**Comment by Nuked88** [comment]
yeah for that i'm trying a different way to do the "auto installation" but i need to test that since I don't want it to screw up the self-installation in windows. One thing still not clear to me tho, you have cuda so i don't understand why that kind of installation has been triggered since is the "cpu" only installation
