### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'moondream_repo.moondream.moondream'

### ISSUE THREAD

**Issue by hiowenluke** [Nuked88/ComfyUI-N-Nodes#43]
When Comfyui is starting, ComfyUI-N-Nodes throw an error:

```
** ComfyUI startup time: 2024-02-27 22:42:23.052276
[2024-02-27 22:42] ** Platform: Windows
[2024-02-27 22:42] ** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
[2024-02-27 22:42] ** Python executable: D:\ComfyUI\ComfyUI\venv\Scripts\python.exe
[2024-02-27 22:42] ** Log path: D:\ComfyUI\ComfyUI\comfyui.log
[2024-02-27 22:42] 
Prestartup times for custom nodes:
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-02-27 22:42] 
[2024-02-27 22:42] Total VRAM 24564 MB, total RAM 65316 MB
[2024-02-27 22:42] xformers version: 0.0.24+cu118
[2024-02-27 22:42] Set vram state to: NORMAL_VRAM
[2024-02-27 22:42] Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
[2024-02-27 22:42] VAE dtype: torch.bfloat16
[2024-02-27 22:42] Using xformers cross attention
[2024-02-27 22:42] Adding extra search path checkpoints d:/stable-diffusion-webui/models/Stable-diffusion
[2024-02-27 22:42] Adding extra search path configs d:/stable-diffusion-webui/models/Stable-diffusion
[2024-02-27 22:42] Adding extra search path vae d:/stable-diffusion-webui/models/VAE
[2024-02-27 22:42] Adding extra search path loras d:/stable-diffusion-webui/models/Lora
[2024-02-27 22:42] Adding extra search path loras d:/stable-diffusion-webui/models/LyCORIS
[2024-02-27 22:42] Adding extra search path upscale_models d:/stable-diffusion-webui/models/ESRGAN
[2024-02-27 22:42] Adding extra search path upscale_models d:/stable-diffusion-webui/models/RealESRGAN
[2024-02-27 22:42] Adding extra search path upscale_models d:/stable-diffusion-webui/models/SwinIR
[2024-02-27 22:42] Adding extra search path embeddings d:/stable-diffusion-webui/embeddings
[2024-02-27 22:42] Adding extra search path hypernetworks d:/stable-diffusion-webui/models/hypernetworks
[2024-02-27 22:42] Adding extra search path controlnet d:/stable-diffusion-webui/extensions/sd-webui-controlnet/models
[2024-02-27 22:42] Adding extra search path clip d:/ComfyUI/ComfyUI/models/clip
[2024-02-27 22:42] Adding extra search path clip_vision d:/ComfyUI/ComfyUI/models/clip_vision
[2024-02-27 22:42] Adding extra search path ipadapter d:/ComfyUI/ComfyUI/models/ipadapter
[2024-02-27 22:42] [AnimateDiff] - [0;33mWARNING[0m - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[2024-02-27 22:42] [Crystools [0;32mINFO[0m] Crystools version: 1.11.0
[2024-02-27 22:42] [Crystools [0;32mINFO[0m] CPU: 13th Gen Intel(R) Core(TM) i9-13900KF - Arch: AMD64 - OS: Windows 10
[2024-02-27 22:42] [Crystools [0;32mINFO[0m] GPU/s:
[2024-02-27 22:42] [Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 4090
[2024-02-27 22:42] [Crystools [0;32mINFO[0m] NVIDIA Driver: 551.61
D:\ComfyUI\ComfyUI\venv\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[2024-02-27 22:42] D:\ComfyUI\ComfyUI\venv\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[2024-02-27 22:42] ### Loading: ComfyUI-Impact-Pack (V4.76.1)
[2024-02-27 22:42] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[2024-02-27 22:42] ### Loading: ComfyUI-Inspire-Pack (V0.64)
[2024-02-27 22:42] [Impact Pack] Wildcards loading done.
[2024-02-27 22:42] D:\ComfyUI\ComfyUI\venv\lib\site-packages\transformers\utils\generic.py:311: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[2024-02-27 22:42] Package diffusers is already installed.
[2024-02-27 22:42] ### Loading: ComfyUI-Manager (V2.7.2)
[2024-02-27 22:42] ### ComfyUI Revision: 1992 [dccca1da] | Released on '2024-02-18'
[2024-02-27 22:42] --------------
[2024-02-27 22:42] [91m ### Mixlab Nodes: [93mLoaded
[2024-02-27 22:42] LaMaInpainting.available True
[2024-02-27 22:42] ClipInterrogator.available True
[2024-02-27 22:42] PromptGenerate.available True
[2024-02-27 22:42] ChinesePrompt.available True
[2024-02-27 22:42] RembgNode_.available True
[2024-02-27 22:42] [93m -------------- [0m
[2024-02-27 22:42] Current version of packaging: 23.2
[2024-02-27 22:42] Version of cpuinfo: Version information not found
[2024-02-27 22:42] Current version of git: 3.1.42
[2024-02-27 22:42] Current version of moviepy: 1.0.3
[2024-02-27 22:42] Current version of cv2: 4.8.0
[2024-02-27 22:42] Current version of skbuild: 0.17.6
[2024-02-27 22:42] Version of typing: Version information not found
[2024-02-27 22:42] Current version of diskcache: 5.6.3
[2024-02-27 22:42] Current version of llama_cpp: 0.2.26+cu118
[2024-02-27 22:42] Current version of timm: 0.9.16
[2024-02-27 22:42] timm is already up-to-date with version 0.9.16
[2024-02-27 22:42] Traceback (most recent call last):
[2024-02-27 22:42]   File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 69, in <module>
    spec.loader.exec_module(module)
[2024-02-27 22:42]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[2024-02-27 22:42]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[2024-02-27 22:42]   File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 12, in <module>
    from moondream_repo.moondream.moondream import Moondream
[2024-02-27 22:42] ModuleNotFoundError: No module named 'moondream_repo.moondream.moondream'
```

The nodes list:
```
Import times for custom nodes:
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\style_aligned_comfy
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\cg-image-picker
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\lora-info
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\wlsh_nodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\cg_custom_core
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_experiments
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-RenderRiftNodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\demofusion-comfyui
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-various
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ArtGallery
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-ZHO
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\cg-quicknodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LCM
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools-save
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-dream-video-batches
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-workspace-manager
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\facerestore_cf
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\Comfyui_ALY
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
[2024-02-27 22:42]    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
[2024-02-27 22:42]    0.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
[2024-02-27 22:42]    0.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\NodeGPT
[2024-02-27 22:42]    0.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Gemini
[2024-02-27 22:42]    0.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DDColor
[2024-02-27 22:42]    0.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes
[2024-02-27 22:42]    0.2 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-InstantID
[2024-02-27 22:42]    0.2 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Seg_VITON
[2024-02-27 22:42]    0.2 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-02-27 22:42]    0.2 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2024-02-27 22:42]    0.3 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts
[2024-02-27 22:42]    0.6 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[2024-02-27 22:42]    0.6 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
[2024-02-27 22:42]    0.6 seconds: D:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
[2024-02-27 22:42]    0.9 seconds: D:\ComfyUI\ComfyUI\custom_nodes\OneButtonPrompt
[2024-02-27 22:42]    1.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
[2024-02-27 22:42]    2.3 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
[2024-02-27 22:42]    2.4 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Crystools
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Nuked88** [comment]
Hi, first of all thanks for the detailed log 😭
Second, do you have a folder called "moondream_repo" in "custom_nodes\ComfyUI-N-Nodes\libs" folder? 
If you do, can you try to delete it and reboot ComfyUI?

**Comment by hiowenluke** [comment]
Yes, its works.
Thanks.
