### ISSUE TITLE
ModuleNotFoundError: No module named 'git' after install

### ISSUE THREAD

**Issue by DrNism** [Nuked88/ComfyUI-N-Nodes#46]
E:\stable-diffusion-webui\comfyui\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 6144 MB, total RAM 32610 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 6GB : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\stable-diffusion-webui\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 4, in <module>
    from .nnodes import init, get_ext_dir,check_and_install,downloader,get_commit,color
  File "E:\stable-diffusion-webui\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\nnodes.py", line 16, in <module>
    import git
ModuleNotFoundError: No module named 'git'

Cannot import E:\stable-diffusion-webui\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes module for custom nodes: No module named 'git'
[ReActor] - STATUS - Running v0.4.1-b11 in ComfyUI
Torch version: 2.2.1+cu121

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): E:\stable-diffusion-webui\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   0.6 seconds: E:\stable-diffusion-webui\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node

Starting server

To see the GUI go to: http://127.0.0.1:8188

**Comment by DrNism** [comment]
Fixed by update libs dependencies
