### ISSUE TITLE
[BUG] inport failed

### ISSUE THREAD

**Issue by derpmagician** [Nuked88/ComfyUI-N-Nodes#67]
this happens after the instalation with the manager
```bash
File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/llama_cpp/llama_cpp.py", line 77, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/llama_cpp/lib/libllama.so': /usBCXX_3.4.29' not found (required by /home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/llama_cpp/lib/libllama.so)

Cannot import /teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI-N-Nodes module for custom nodes: Failed to load shared library '/homee-packages/llama_cpp/lib/libllama.so': /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/zeus/mins/llama_cpp/lib/libllama.so)
```

**Comment by secretivebanana** [comment]
Had a similar or same error. I fixed it by:
1. Close ComfyUI.
2. Activate ComfyUI virtual environment (venv) from venv/scripts/activate.bat.
3. In the command window: pip uninstall llama-cpp-python.
4. Then again in command window: pip install llama-cpp-python.
5. Re-open ComfyUI.

**Comment by CheoWalker** [comment]
`I am seeing this for my Import Error

Error message occurred while importing the 'ComfyUI-N-Nodes' module.

Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2141, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-n-nodes\__init__.py", line 22, in <module>
    check_and_install('scikit-build',"skbuild")
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-n-nodes\nnodes.py", line 145, in check_and_install
    library_module = importlib.import_module(import_name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cheow\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\cheow\AppData\Local\Programs\Python\Python312\Lib\site-packages\skbuild\__init__.py", line 10, in <module>
    from .setuptools_wrap import setup
  File "C:\Users\cheow\AppData\Local\Programs\Python\Python312\Lib\site-packages\skbuild\setuptools_wrap.py", line 22, in <module>
    import setuptools
  File "C:\Users\cheow\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
    import setuptools.version
  File "C:\Users\cheow\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\version.py", line 1, in <module>
    import pkg_resources
  File "C:\Users\cheow\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?`

**Comment by gameLvr85** [comment]
Running this command in comfyui-n-nodes
......\python_embeded\python.exe -m pip install -r requirements.txt

Requirement already satisfied: py-cpuinfo in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (9.0.0)
Requirement already satisfied: gitpython in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (3.1.44)
Requirement already satisfied: moviepy in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: opencv-python in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (4.11.0.86)
Requirement already satisfied: scikit-build in f:\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 5)) (0.18.1)
Collecting typing (from -r requirements.txt (line 6))
Using cached typing-3.7.4.3.tar.gz (78 kB)
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [11 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 14, in
File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools_init_.py", line 16, in
import setuptools.version
File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in
import pkg_resources
File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources_init_.py", line 2191, in
register_finder(pkgutil.ImpImporter, find_on_path)
^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
