### ISSUE TITLE
Video Path already deleted [BUG]

### ISSUE THREAD

**Issue by gillesvandevoorde** [Nuked88/ComfyUI-N-Nodes#68]
**Describe the bug**
Images are not retrieved from video and error is shown

**To Reproduce**
1. load video node
2. select mp4 file
3. run pipe

**Expected behavior**
creates images from video

**Full log**

Starting server

To see the GUI go to: http://127.0.0.1:8189
got prompt
The video has 25 frames per second.
Video Path already deleted
338 frames have been extracted from the video and saved in E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\temp\n-suite\frames_out\test
MoviePy - Writing audio in E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\temp\n-suite\frames_out\test\audio.mp3
MoviePy - Done.
images_limit 6
WARNING: The batch size is greater than the number of frames requested. Batch size has been reduced to the number of images_limit.
!!! Exception during processing!!! chunk expects `chunks` to be greater than 0, got: 0
Traceback (most recent call last):
  File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\video_node_advanced.py", line 535, in encode
    i_tensor_batches = torch.chunk(i_tensor, n_chunks, dim=0)
RuntimeError: chunk expects `chunks` to be greater than 0, got: 0

Prompt executed in 8.23 seconds

**error message in UI:**
Error occurred when executing LoadVideo [n-suite]:

chunk expects `chunks` to be greater than 0, got: 0

File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\AI\SD\stable-diffusion-webui-master\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\video_node_advanced.py", line 535, in encode
i_tensor_batches = torch.chunk(i_tensor, n_chunks, dim=0)

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
MP4 file, have it with multiple files. Other mp4s worked.

**Comment by gillesvandevoorde** [comment]
Video path already deleted is not relevant (always shown)
fully restarting A1111 (twice since it had a permission error in venv) ended up fixing the issue.
