### ISSUE TITLE
[BUG] Value not in list: video:

### ISSUE THREAD

**Issue by noarche** [Nuked88/ComfyUI-N-Nodes#73]
**Describe the bug**

I don't think its a bug but I don't know how to fix it. If anyone has any suggestions as to what I should try to do they are much appreciated. 

I keep getting this error:

**To Reproduce**

1. Go to 'load video'
2. Click on 'load video'
3. Scroll down to 'read the console error'

**Expected behavior**

The node loads fine however when I load any video I get the following error:

`[2024-08-06 03:28]   - **Value not in list: video: 'Simple Vid 3.mp4' not in []`**
`[2024-08-06 03:28] Output will be ignored`

**Full log**

```
F:\_cozyai\ComfyUI_windows_portable>SET JOV_GIFSKI=C:\gifski\gifski.exe

F:\_cozyai\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --output-directory F:\_cozyai\output --input-directory F:\_cozyai\input
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-08-06 03:47:15.191950
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: F:\_cozyai\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\_cozyai\ComfyUI_windows_portable\ComfyUI
** Log path: F:\_cozyai\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.3 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 65456 MB
pytorch version: 2.4.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\web
[Crystools INFO] Crystools version: 1.16.6
[Crystools INFO] CPU: AMD Ryzen 9 5900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3060
[Crystools INFO] NVIDIA Driver: 560.70
Comfy-Easy-Use v1.2.1: Loaded
### Loading: ComfyUI-Impact-Pack (V6.0)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
A new version of Albumentations is available: 1.4.13 (you have 1.4.12). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
Total VRAM 12288 MB, total RAM 65456 MB
pytorch version: 2.4.0+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.48.5)
### ComfyUI Revision: 2474 [2d75df45] | Released on '2024-08-05'
------------------------------------------
### N-Suite Revision: 59ecf716
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.43
Current version of moviepy: 1.0.3
Current version of cv2: 4.10.0
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
Current version of skbuild: 0.18.0
Version of typing: Not found
Current version of diskcache: 5.6.3
Current version of llama_cpp: 0.2.26+cu118
Current version of timm: 1.0.8
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
ComfyUI-N-Sidebar is loading...
[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
Torch version: 2.4.0+cu118
### ComfyUI-Workflow-Encrypt: Copy .js from 'F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Encrypt\js\comfyui-workflow-encrypt.js' to 'F:\_cozyai\ComfyUI_windows_portable\ComfyUI\web\extensions\comfyui-workflow-encrypt'
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
Not found test nodes.
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
# 😺dzNodes: MSSpeech TTS: Load voice setting -> F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MSSpeech_TTS\voicelist.ini
# 😺dzNodes: MSSpeech TTS: 23 voice load successfully.
[tinyterraNodes] Loaded
# 😺dzNodes: WordCloud ->  find 133 fonts in C:\Windows\fonts
[comfy_mtb] | INFO -> loaded 84 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

[rgthree] Loaded 40 exciting nodes.

Searge-SDXL v4.3.1 in F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: Finished. Loaded 217 nodes successfully.
[WAS Extras] Loading extra custom nodes...
[WAS Extras]  Import times for extras:
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\ConditioningBlend.py
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\DebugThis.py
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\VAEEncodeForInpaint.py
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\VividSharpen.py
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\ksampler_sequence.py
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras\BLVaeEncode.py

Import times for custom nodes:
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutoTrimBG
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Sidebar
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-webui-color-enhance
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-off-suite
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TRA
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\qq-nodes-comfyui
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\WAS_Extras
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TranscriptionTools
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Extra-Samplers
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence-2
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_WordCloud
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Workflow-Encrypt
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.0 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.1 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.1 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.1 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DDColor
   0.1 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.1 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Whisper
   0.2 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_MSSpeech_TTS
   0.2 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Pronodes
   0.3 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.4 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.4 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Mana-Nodes
   0.4 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_bmab
   0.5 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.5 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   0.7 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
   0.8 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\audio-separation-nodes-comfyui
   1.2 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.9 seconds: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\Jovimetrix

Setting output directory to: F:\_cozyai\output
Setting input directory to: F:\_cozyai\input
Starting server

To see the GUI go to: http://127.0.0.1:8188
failed to load comfyui_controlnet_aux
[ERROR:0@12.052] global obsensor_uvc_stream_channel.cpp:158 cv::obsensor::getStreamChannelGroup Camera index out of range
[ERROR:0@12.055] global obsensor_uvc_stream_channel.cpp:158 cv::obsensor::getStreamChannelGroup Camera index out of range
FETCH DATA from: F:\_cozyai\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
failed to load comfyui_controlnet_aux
Error handling request
Traceback (most recent call last):
  File "F:\_cozyai\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 456, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\_cozyai\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\_cozyai\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\_cozyai\ComfyUI_windows_portable\ComfyUI\server.py", line 45, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\_cozyai\ComfyUI_windows_portable\ComfyUI\server.py", line 57, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\_cozyai\ComfyUI_windows_portable\ComfyUI\server.py", line 308, in view_image
    with Image.open(file) as img:
         ^^^^^^^^^^^^^^^^
  File "F:\_cozyai\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3498, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'F:\\_cozyai\\input\\n-suite\\Simple Vid 3.mp4'
got prompt
Failed to validate prompt for output 14:
* LoadVideo [n-suite] 45:
  - Value not in list: video: 'Simple Vid 3.mp4' not in []
Output will be ignored
Failed to validate prompt for output 16:
Output will be ignored
Prompt executed in 0.00 seconds
```

**Screenshots**

![Aug-06-2024-Tue-0328AM](https://github.com/user-attachments/assets/5b683d45-02f4-4ff2-82bb-d14e0a656291)
![Aug-06-2024-Tue-0328AM (1)](https://github.com/user-attachments/assets/98d08b7c-956f-4553-9240-a43177337915)
![Aug-06-2024-Tue-0328AM (2)](https://github.com/user-attachments/assets/11b30cec-bf4b-440c-b649-914cf7cde41b)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser firefox dev edition 
 - Version 129.0b9

**Additional context**
I have tried completely removing and reinstalling, that went smooth but gives the same result. Ive tried diff formats of video, diff sizes. This seems to be the only node Ive ran into that gives me trouble figuring out. 

I also checked \ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py

I searched for mp4 - no hits
I search png and jpg both got hits
I search extension and found this line but not sure if it means anything here.

![Aug-06-2024-Tue-0357AM](https://github.com/user-attachments/assets/98f07f4d-a36d-49f2-9d24-7e39cb7234a2)

\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL

Thanks

**Comment by noarche** [comment]
I just did Yet Another Fresh Install.

**Comment by noarche** [comment]
Well the fresh install did not work, Same exact result twice in a row. 
It felt like it was going alot smoother and almost nothing gave any errors until I press load video with this node. 

If I try to use VHS to load the video it loads fine but VHS doesn't have a save node, thus your save node then throws the same error. 

Please let me know if this makes sense. Leaving ticket open.  Thanks

**Comment by Nuked88** [comment]
I think the problem is the encoding of the video you are using, if you notice even the preview gives error and that is given by the browser, so even your browser can't display that file. I suggest you try to convert it back to MP4 with other programs like handbrake and then try again with the new video.

**Comment by noarche** [comment]
That was the first thing I thought too, and I thought it could of been a problem with pillow but in the end I changed nodes to a completely diff node I came across to load and save video and was able to work around this node not working _for me_. 

When I changed nodes I noticed the frame inter. gave same error. 

I am not sure what caused it but thought it could be worth mentioning. 

Thanks
