### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shivanraptor** [Nuked88/ComfyUI-N-Nodes#77]
**Describe the bug**
After installing ComfyUI-N-Nodes via Custom Node Manager, stopped the server and installed `llama-cpp-python` via pip successfully, I started the server but the start log had an error:
```
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**To Reproduce**
1. Go to ComfyUI, install ComfyUI-N-Nodes via Custom Node Manager.
2. Stopped the server
3.  Installed `llama-cpp-python` via pip successfully
4. See error: TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Expected behavior**
Should not have TypeError

**Full log**
This is MANDATORY. By log I mean all the text in the console from the time ComfyUI was started until the time of the reported bug.
>>Bug reports that do not have this log will be closed.<<
```
Traceback (most recent call last):
  File "/Users/adv/Documents/GitHub/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 64, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/adv/Documents/GitHub/ComfyUI/custom_nodes/ComfyUI-N-Nodes/py/gptcpp_node.py", line 11, in <module>
    import joytag_models
  File "/Users/adv/Documents/GitHub/ComfyUI/custom_nodes/ComfyUI-N-Nodes/libs/joytag_models.py", line 17, in <module>
    class VisionModel(nn.Module):
  File "/Users/adv/Documents/GitHub/ComfyUI/custom_nodes/ComfyUI-N-Nodes/libs/joytag_models.py", line 28, in VisionModel
    def load_model(path: Path | str, device: str | None = None) -> 'VisionModel':
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.6.1
 - Brave Browser 1.69.162
 

**Additional context**
- The ComfyUI can be used without problems, including the N Nodes.

**Comment by Nuked88** [comment]
Hi! Are you using a Python version lower than 3.10?

**Comment by shivanraptor** [comment]
> Hi! Are you using a Python version lower than 3.10?

Yes, version 3.9.19 via `virtualenv`

**Comment by Nuked88** [comment]
That's the problem, that part of the code is only 3.10+ compatible.

**Comment by shivanraptor** [comment]
After upgrading to Python 3.12 and re-install all pip packages, it works fine without errors. Thanks.
