### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by noxouille** [Nuked88/ComfyUI-N-Nodes#8]
After installing the nodes and restarting comfyui, I got the following error msg:

```bash
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
Traceback (most recent call last):
  File "/usr/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/notebooks/notebooks/ComfyUI')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/notebooks/notebooks/ComfyUI/nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/notebooks/notebooks/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 73, in <module>
    check_and_install('scikit-build',"skbuild")
  File "/notebooks/notebooks/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 20, in check_and_install
    importlib.import_module(import_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/skbuild/__init__.py", line 10, in <module>
    from .setuptools_wrap import setup
  File "/usr/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 31, in <module>
    from .command import (
  File "/usr/local/lib/python3.10/dist-packages/skbuild/command/test.py", line 5, in <module>
    from setuptools.command.test import test as _test
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/test.py", line 11, in <module>
    from pkg_resources import (
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 622, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 615, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 671, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2075, in find_distributions
    importer = get_importer(path_item)
  File "/usr/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'

Cannot import /notebooks/notebooks/ComfyUI/custom_nodes/ComfyUI-N-Nodes module for custom nodes: 'PosixPath' object has no attribute 'startswith'
```

Any ideas what could be the issue?

**Comment by Nuked88** [comment]
where are you using ComfyUI? I think that your system have a different version of importlib of the one shipped in the comfyui all-in-one package.
i have importlib-metadata==6.8.0 try to install this version with pip

**Comment by noxouille** [comment]
> where are you using ComfyUI? I think that your system has a different version of importlib from the one installed by default in the comfyui all-in-one package. i have importlib-metadata==6.8.0 try to install this version with pip

I am running comfyui on paperspace. Tried installing importlib-metadata as you suggested but still got the same error.
```
!pip install importlib-metadata==6.8.0

Requirement already satisfied: importlib-metadata==6.8.0 in /usr/local/lib/python3.10/dist-packages (6.8.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata==6.8.0) (3.17.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**Comment by Nuked88** [comment]
uhm,  can you try to install scikit-build manually? the error is just related to that, try `pip install scikit-build`
Probably paperspace doesn't like command like the one i used for the auto-install of the modules 🤔

**Comment by noxouille** [comment]
after manually install scikit-build, the error msg now seems really similar with the previous one, but the custom nodes seemed to be loaded, although I'm not sure that all the nodes were available (for example, in the Add Nodes > N-Suite > Video, I see only Frame interpolator, and no other nodes such as load video).

```
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
skbuild is already installed.
Downloading dependencies...
Loaded 3.x/4.x HD model.
'PosixPath' object has no attribute 'startswith'
No module named 'llama_cpp'
```

**Comment by Nuked88** [comment]
ok, i've added a trackback for detect where the damn error is, can you du a `git pull ` and try to run it again so that we can see where the error is coming from? Thanks!

**Comment by noxouille** [comment]
```bash
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
skbuild is already installed.
Loaded 3.x/4.x HD model.
Traceback (most recent call last):
  File "/usr/lib/python3.10/pkgutil.py", line 417, in get_importer
    importer = sys.path_importer_cache[path_item]
KeyError: PosixPath('/notebooks/notebooks/ComfyUI')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/notebooks/notebooks/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 90, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/notebooks/notebooks/ComfyUI/custom_nodes/ComfyUI-N-Nodes/py/video_node.py", line 12, in <module>
    from moviepy.editor import VideoFileClip, AudioFileClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/usr/local/lib/python3.10/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python3.10/dist-packages/moviepy/config.py", line 35, in <module>
    from imageio.plugins.ffmpeg import get_exe
  File "/usr/local/lib/python3.10/dist-packages/imageio/plugins/ffmpeg.py", line 143, in <module>
    import imageio_ffmpeg
  File "/usr/local/lib/python3.10/dist-packages/imageio_ffmpeg/__init__.py", line 7, in <module>
    from ._io import count_frames_and_secs, read_frames, write_frames
  File "/usr/local/lib/python3.10/dist-packages/imageio_ffmpeg/_io.py", line 8, in <module>
    from ._parsing import LogCatcher, cvsecs, parse_ffmpeg_header
  File "/usr/local/lib/python3.10/dist-packages/imageio_ffmpeg/_parsing.py", line 5, in <module>
    from ._utils import logger
  File "/usr/local/lib/python3.10/dist-packages/imageio_ffmpeg/_utils.py", line 7, in <module>
    from pkg_resources import resource_filename
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 622, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 615, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 671, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2075, in find_distributions
    importer = get_importer(path_item)
  File "/usr/lib/python3.10/pkgutil.py", line 421, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1632, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1504, in __init__
  File "<frozen importlib._bootstrap_external>", line 182, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

**Comment by Nuked88** [comment]
so is moviepy related... 
i digged deeeep, i found that your _io.py from imageio_ffmpeg is different from mine, so maybe youcan try to update that.
my version is imageio-ffmpeg==0.4.9 and just for info my imageio module is imageio==2.31.1
I guess that paperspace comes with some of this package already installed...

if this not solve the problem someone said that could be related to a non standard pathlib moduled installed,
try to remove pathlib if there are one installed besize the default one with 
`pip uninstall pathlib`

**Comment by noxouille** [comment]
my `imageio-ffmpeg` is also `0.4.9` , and `imageio==2.31.5`. 
I tried to install `imageio==2.31.1` and still no luck.
`moviepy==1.0.3`

there are no other pathlib installed, so I'm not sure what to do now.
```
!pip uninstall -y pathlib

WARNING: Skipping pathlib as it is not installed.
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

```

**Comment by Nuked88** [comment]
Soooo, good news, i'm pretty sure that there is something wrong with your paperspace notebook instance.
I tryed to create a new notebook on paperspace using a prebuild container image with Python 3.10 in my case i've used ( cyberes/gradient-base-py3.10:latest). 
Then i've used the notebook taken from the ComfyUI repo and i've cloned this repo in the custom-nodes in the second block (the one with all the models link)
Finally i've started, with cloudflared, ComfyUI and there was no error (except for the llama one but that one was expected)
And all the video nodes was working fine!

**Comment by noxouille** [comment]
ok, I'll check that out, thanks!
