### ISSUE TITLE
[BUG] Noob Needs Help - No Llama

### ISSUE THREAD

**Issue by reefor** [Nuked88/ComfyUI-N-Nodes#80]
I'm running Comfyui Portable on an old windows machine with Nvidia.

I love these nodes because it lets me do stuff with low vram & ram, but everytime I install this I get an error message that it can't find Llama. I even tried installing comfyui-llama (custom node) but that didn't help at all.

When I try to load a workflow with your nodes the screen freezes. The right side with the node manager still works but the main screen is frozen. I can only unfreeze it by loading a workflow for liveportrait, hitting refresh, then loading a workflow with your nodes. Sometimes I have to do it more than once.

There are other issues, like the workflow with your nodes taking a long time to run.

I'm really not sure if any of these problems are related, but there's only 1 way to find out, which is to fix the missing llama problem.

I'm guessing I have to install llama somewhere but not sure where or what version of llama. Can anyone give me the command to run and tell me which folder to run it in please?

C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-22 09:47:05.196445
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16271 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\web
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Adding C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Loaded ControlNetPreprocessors nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.11.4)
Loaded ImpactPack nodes from [Impact Pack] Wildcards loading done.C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2018, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 9, in <module>
    from diffusers import ConsistencyDecoderVAE
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)
### Loading: ComfyUI-Impact-Pack (V7.11.4)
[Impact Pack] Wildcards loading done.
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Total VRAM 6144 MB, total RAM 16271 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 : cudaMallocAsync
### ComfyUI Revision: 2817 [6ee066a1] | Released on '2024-11-08'
------------------------------------------
### N-Suite Revision: ae7cc848
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.43
Current version of moviepy: 1.0.3
Current version of cv2: 4.10.0
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Current version of skbuild: 0.18.1
Version of typing: Not found
Current version of diskcache: 5.6.3
Installing llama_cpp...
Python version: None
OS: Windows
OS bit: 64
Platform tag: cp312-cp312-win_amd64
Unsupported Python version. Please use Python 3.9, 3.10 or 3.11.
Current version of timm: 1.0.11
Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 64, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 4, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
[tinyterraNodes] Loaded

[rgthree-comfy] Loaded 42 epic nodes. 🎉

Import times for custom nodes:
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Img2PaintingAssistant
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-copilot
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds (IMPORT FAILED): C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Anyline
   0.5 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   0.6 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.7 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   1.2 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
   3.3 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes

**Additional context**

**Comment by reefor** [comment]
For those that might think this question is too stupid to answer. C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py points to the file that's requesting llama, not where it's looking for llama.

I'm a noob but I'm learning. I just can't find anything that point to where it should be or what version.

**Comment by reefor** [comment]
OK, so I ran the pip install for llama and it told me all requirements are already satisfied. Still getting the can't find llama error.

Someone else told me that the python version error comes from Comfyui-N-Nodes and I have to manually install an earlier version and create a venv. I know nothing about creating a venv other than I'm sure I didn't do it when I started using Comfy Portable, unless it was automatic in the requirements.txt that I ran, or one of the BATs.

So is Comfyui-N-Nodes incompatible with Comfyui Portable since I don't think I'm running it in a venv?

**Comment by Nuked88** [comment]
Hi, sorry but this is a messy time for me!
The problem is that the repository I use to install llama_cpp_python supports python up to version 3.11
If you don't care about using the GPU for text generation and just want to remove the error you need to run the command
python.exe -s -m pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu 

from the **\ComfyUI_windows_portable\python_embeded** folder (where python.exe is located).

**Comment by reefor** [comment]
> Hi, sorry but this is a messy time for me! The problem is that the repository I use to install llama_cpp_python supports python up to version 3.11 If you don't care about using the GPU for text generation and just want to remove the error you need to run the command python.exe -s -m pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
> 
> from the **\ComfyUI_windows_portable\python_embeded** folder (where python.exe is located).

Thanks for your help, but it didn't work. Still getting the error message and comfyui still locking up when I try to load a workflow with the n-nodes. This is the message I got after running the command in the python_embeded folder

D:\Comfyui\ComfyUI_windows_portable\python_embeded>python.exe -s -m pip install llama-cpp-python --extra-index-url

Usage:
  D:\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  D:\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  D:\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe -m pip install [options] [-e] <vcs project url> ...
  D:\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe -m pip install [options] [-e] <local project path> ...
  D:\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe -m pip install [options] <archive url/path> ...

--extra-index-url option requires 1 argument
